name: Python Package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:

    - uses: actions/checkout@v5

    - name: Python 
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install requirements
      run: |
        pip install -r backend/requirements.txt
        pip install -r frontend/requirements.txt

    - name: test with pytest
      run: |
        pip install pytest pytest-cov
        pytest

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push frontend
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: true
        tags: khrisssss/ml-pipeline-frontend:latest

    - name: Build and push backend
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        file: ./backend/Dockerfile
        push: true
        tags: khrisssss/ml-pipeline-backend:latest

