name: Python Package

on:
    workflow_dispatch:

jobs:
  build:

      runs-on: ubuntu-latest
      
      steps:

      - uses: actions/checkout@v5

      - name: Python 
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install requirements
        run: |
          pip install -r backend/requirements.txt

      - name: train model and save it
        run: |
          python backend/ml/train.py
      